// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://qdurxqgpqflomjwitaja.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFkdXJ4cWdwcWZsb21qd2l0YWphIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg4MDA0ODYsImV4cCI6MjA3NDM3NjQ4Nn0.mV81MvH-AJLTuYQiZpiDSD5hXX3iFuPfUtAHDwxW86s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);